# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('last_session_key', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('color_list', models.CharField(default='', max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('currency', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('id_technology', models.IntegerField(default=0)),
                ('id_material', models.IntegerField(default=0)),
                ('id_color', models.CharField(default='', max_length=20)),
                ('dimensions', models.CharField(default='', max_length=20)),
                ('file_path', models.CharField(default='', max_length=200)),
                ('last_session_key', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('id_client', models.IntegerField(default=0)),
                ('list_models3d_quantity', models.CharField(default='', max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('currency', models.CharField(default='', max_length=20)),
                ('last_session_key', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('currency', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
