# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='part_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
