# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_model3d_part_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model3d',
            old_name='part_name',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='last_session_key',
        ),
    ]
