# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_auto_20170829_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model3d',
            old_name='id_color',
            new_name='color',
        ),
    ]
