# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_auto_20170829_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='file',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
