# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import sp3d_quotation.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_auto_20170902_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(blank=True, storage=sp3d_quotation.storage_backends.PrivateMediaStorage(), upload_to=b''),
        ),
    ]
