# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_bulk_files_quote_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_form',
            name='request_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quote_form',
            name='service',
            field=models.CharField(default='', max_length=200),
        ),
    ]
