# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_technologyyaml'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyyaml',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
