# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_technologyyaml_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
