# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_auto_20180131_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
