# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0014_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='tag_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tag_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
