# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-20 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0015_auto_20180205_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_form',
            name='contact',
            field=models.CharField(default='', max_length=200),
        ),
    ]
