"""
Django settings for sp3d_quotation project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'el=vat2*z9v(of&sqksxsqmry41tp!*+&+_arw%mk0+mac6*ht'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '52.220.179.77',
    '52.220.96.102',
    '192.168.0.20',
    '127.0.0.1',
    '192.168.0.112',
    'django-env.fguh7yrrpd.ap-southeast-1.elasticbeanstalk.com',
    'localhost',
    'prototype-in-asia.com',
    'www.prototype-in-asia.com',
    'prototypeinasia.com',
    'www.prototypeinasia.com',
    'made-in-sg.com',
    'www.made-in-sg.com',
    'prototype.sg',
    'www.prototype.sg',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quotation',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sp3d_quotation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sp3d_quotation.context_processors.google_analytics',
            ],
            'builtins': ['django.contrib.staticfiles.templatetags.staticfiles'],
        },
    },
]

WSGI_APPLICATION = 'sp3d_quotation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Quotation',
        'USER': 'root',
        'PASSWORD': 'SpareParts3D#',
        'HOST': 'quotation.csgmjvodxypo.ap-southeast-1.rds.amazonaws.com',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# STATIC_URL = '/static/'
STATIC_ROOT=os.path.join(BASE_DIR,'static/')

# AWS S3 STORAGE
AWS_ACCESS_KEY_ID = 'AKIAJQUVRVZZ4ZTEA5OQ' # OR os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'sp3dquotation'
AWS_S3_CUSTOM_DOMAIN = 's3-ap-southeast-1.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}


#################################################ACTIVATE THIS FOR PROD####################################
#if you want static files on S3:
# AWS_STATIC_LOCATION = 'static'
# STATICFILES_STORAGE = 'sp3d_quotation.storage_backends.StaticStorage'
# STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_STATIC_LOCATION)

########################################################DEACTIVATE FOR PROD########################################
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'quotation','static'),
]
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    # 'django.contrib.staticfiles.finders.AppDirectoriesFinder',    #causes verbose duplicate notifications in django 1.9
)

#################################################ACTIVATE THIS FOR PROD####################################
AWS_PUBLIC_MEDIA_LOCATION = 'media/public'
DEFAULT_FILE_STORAGE = 'sp3d_quotation.storage_backends.PublicMediaStorage'

AWS_PRIVATE_MEDIA_LOCATION = 'media/private'
PRIVATE_FILE_STORAGE = 'sp3d_quotation.storage_backends.PrivateMediaStorage'
AWS_QUERYSTRING_EXPIRE = 259200 #in seconds. 72h
###########################################################################################################

# for HTTPS REDIRECTION
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
# activate this if post requests only for HTTPS context:
# CSRF_COOKIE_SECURE = True

FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  #will raise suspicious error
# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 5242880
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160

####################################################################################################
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'hello@sp3d.co'
EMAIL_HOST_PASSWORD = 'epdbynrydgeugqjf'
DEFAULT_FROM_EMAIL = "service@sp3d.co"
