# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_auto_20171112_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digital.ClientPartStatus'),
        ),
    ]
