# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_auto_20171112_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='model',
            field=models.ManyToManyField(blank=True, to='digital.Model'),
        ),
    ]
