# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital', '0008_auto_20171113_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('mm', 'mm'), ('inch', 'inch')], default='INFO', max_length=20, null=True)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('long_description', models.TextField(default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.Part')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.ClientPartStatus')),
            ],
        ),
    ]
