# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organisation_industry'),
        ('digital', '0010_auto_20171116_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='partfamily',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Industry'),
        ),
    ]
