# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organisation_industry'),
        ('digital', '0011_partfamily_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organisation'),
        ),
    ]
