# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0013_auto_20171121_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='model',
            new_name='appliance',
        ),
    ]
