# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organisation_industry'),
        ('digital', '0015_auto_20171121_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('industry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Industry')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.PartType'),
        ),
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together=set([('name', 'industry')]),
        ),
    ]
