# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0016_auto_20171121_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('WHITE', 'White'), ('BLACK', 'Black')], max_length=20, null=True)),
                ('is_visual', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='characteristics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.Characteristics'),
        ),
    ]
