# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0017_auto_20171121_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='color',
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='color',
            field=models.CharField(blank=True, choices=[('GREEN', 'Green'), ('WHITE', 'White'), ('BLACK', 'Black'), ('NA', 'na')], max_length=20, null=True),
        ),
    ]
