# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0018_auto_20171122_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='partbulkfile',
            name='data',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='partbulkfile',
            name='type',
            field=models.CharField(choices=[('BULK', 'bulk files'), ('MATERIAL', 'material files'), ('3D', '3d model'), ('2D', '2d drawings'), ('STL', 'STL file')], default='BULK', max_length=20),
        ),
    ]
