# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0019_auto_20171122_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partbulkfile',
            name='data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
