# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0020_auto_20171122_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='flame_retardancy',
            field=models.CharField(blank=True, choices=[('NA', 'n/a'), ('HB', 'HB'), ('V0', 'V0'), ('V1', 'V1'), ('V2', 'V2')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='is_chemical_resistant',
            field=models.BooleanField(default=False, verbose_name='Chemical Resistant'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='is_flame_retardant',
            field=models.BooleanField(default=False, verbose_name='Flame Retardant'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='is_food_grade',
            field=models.BooleanField(default=False, verbose_name='Food Grade'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='is_transparent',
            field=models.BooleanField(default=False, verbose_name='Transparent'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='is_water_resistant',
            field=models.BooleanField(default=False, verbose_name='Water Resistant'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='max_temp',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='min_temp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='temp_unit',
            field=models.CharField(blank=True, choices=[('\xb0C', 'Celsius'), ('\xb0F', 'Fahrenheit')], default='\xb0C', max_length=5),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='color',
            field=models.CharField(blank=True, choices=[('NA', 'n/a'), ('GREEN', 'Green'), ('WHITE', 'White'), ('BLACK', 'Black')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='is_visual',
            field=models.BooleanField(default=False, verbose_name='Visual part'),
        ),
    ]
