# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0022_auto_20171123_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='grade',
        ),
    ]
