# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0023_remove_part_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='environment',
        ),
    ]
