# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0024_remove_part_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='dimension_unit',
            field=models.CharField(choices=[('mm', 'mm'), ('inch', 'inch')], default='mm', max_length=5),
        ),
    ]
