# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0026_part_final_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='notify_status_to_client',
            field=models.BooleanField(default=False, verbose_name='Notify Part Status to Client'),
        ),
    ]
