# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0027_part_notify_status_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='final_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jb.FinalCard'),
        ),
    ]
