# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0029_auto_20171128_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='is_elastic',
            field=models.BooleanField(default=False, verbose_name='Elastic'),
        ),
    ]
