# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0031_auto_20171129_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristics',
            old_name='is_elastic',
            new_name='is_rubbery',
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='is_rubbery',
            field=models.BooleanField("Rubbery Like", default=False, blank=True),
        ),
    ]
