# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0033_auto_20171204_0705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together=set([('name', 'appliance_family')]),
        ),
    ]
