# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0035_remove_parttype_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='techno_material',
        ),
    ]
