# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0038_auto_20171204_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='characteristics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='digital.Characteristics'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.Characteristics'),
        ),
    ]
