# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0039_auto_20171204_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='part',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='digital.Part'),
        ),
    ]
