# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 09:46
from __future__ import unicode_literals

from django.db import migrations
from digital.models import Characteristics, Part


def populate_characteristics(apps, schema_editor):
    for part in Part.objects.all():
        if part.characteristics:
            part.characteristics.part = part
            part.characteristics.save()

class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0040_characteristics_part'),
    ]

    operations = [
        migrations.RunPython(populate_characteristics),
    ]
