# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0041_auto_20171204_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='part_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_type_characteristics', to='digital.PartType'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.ApplianceFamily'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organisation'),
        ),
        migrations.AlterField(
            model_name='appliancefamily',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Industry'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_characteristics', to='digital.Part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_characteristics', to='digital.Characteristics'),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='part',
            name='final_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jb.FinalCard'),
        ),
        migrations.AlterField(
            model_name='part',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jb.Material'),
        ),
        migrations.AlterField(
            model_name='part',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organisation'),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='digital.ClientPartStatus'),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.PartType'),
        ),
        migrations.AlterField(
            model_name='partbulkfile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partevent',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.ClientPartStatus'),
        ),
        migrations.AlterField(
            model_name='partimage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='appliance_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.ApplianceFamily', verbose_name='Appliance Family'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_type_characteristics', to='digital.Characteristics'),
        ),
    ]
