# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0043_auto_20171205_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='max_temp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Operating Temperature'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='min_temp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Operating Temperature'),
        ),
    ]
