# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0045_auto_20171205_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='reference',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
