# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0046_auto_20171207_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='keywords',
            field=models.CharField(default='', max_length=200),
        ),
    ]
