# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171207_0227'),
        ('digital', '0048_auto_20171213_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='reference',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set([('reference', 'organisation')]),
        ),
    ]
