# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0050_auto_20171213_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='Selling price (in US$)')),
                ('selling_volumes', models.IntegerField(blank=True, null=True, verbose_name='Yearly Selling Volumes')),
                ('part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_financial_card', to='digital.Part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='financial_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_financial_card', to='digital.FinancialCard'),
        ),
    ]
