# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0051_auto_20180101_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='production_cost',
            field=models.FloatField(default=0.0, verbose_name='Selling price (in US$)'),
        ),
        migrations.AddField(
            model_name='financialcard',
            name='sp3d_selling_price',
            field=models.FloatField(blank=True, null=True, verbose_name='SP3D Selling price to OEM (US$)'),
        ),
    ]
