# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0052_auto_20180102_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliancefamily',
            name='retail_price',
            field=models.FloatField(default=0.0, verbose_name='Average Retail Price (US$)'),
        ),
    ]
