# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0053_appliancefamily_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='selling_repriced',
            field=models.FloatField(blank=True, null=True, verbose_name='Repriced selling price (in US$)'),
        ),
    ]
