# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171207_0227'),
        ('digital', '0054_financialcard_selling_repriced'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_plus_ratio', models.FloatField(default=0.3, verbose_name='Percentage of Cost to find cost+')),
                ('sp3d_margin_share', models.FloatField(default=0.5, verbose_name='Ratio of sp3d share in margin')),
                ('appliance_repricing_maxvalue_ratio', models.FloatField(default=0.05, verbose_name='Percentage Value of Appliance as a max repricing')),
                ('organisation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_financial_settings', to='users.Organisation')),
            ],
        ),
    ]
