# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0056_financialsettings_repricing_new_max_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='former_moq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Former Minimum Quantity Order'),
        ),
        migrations.AddField(
            model_name='financialcard',
            name='former_production_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Former Production Cost (in US$)'),
        ),
        migrations.AlterField(
            model_name='financialcard',
            name='production_cost',
            field=models.FloatField(default=0.0, verbose_name='SP3D production cost (in US$)'),
        ),
        migrations.AlterField(
            model_name='financialsettings',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_settings', to='users.Organisation'),
        ),
    ]
