# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0058_financialcard_former_tco'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='yearly_stock_price_ratio',
            field=models.FloatField(default=0.2, verbose_name='Ratio of stock price per year'),
        ),
    ]
