# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0059_financialsettings_yearly_stock_price_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='yearly_selling_decrease_ratio',
            field=models.FloatField(default=0.1, verbose_name='Yearly Selling Decrease Ratio'),
        ),
    ]
