# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0061_auto_20180105_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='cost_saving',
            field=models.FloatField(default=0, verbose_name='5y cost saving'),
        ),
    ]
