# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0062_financialcard_cost_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialcard',
            name='cost_saving',
        ),
        migrations.AddField(
            model_name='financialcard',
            name='cost_saving_5y',
            field=models.FloatField(default=0, verbose_name='cost savings on 5 years'),
        ),
    ]
