# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 03:23
from __future__ import unicode_literals

import digital.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sp3d.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital', '0063_auto_20180105_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, storage=sp3d.storage_backends.PrivateMediaStorage(bucket='sp3d-clients'), upload_to=digital.models.get_analysisexport_path)),
                ('bulk_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.BulkPartUpload')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
