# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 03:51
from __future__ import unicode_literals

import digital.models
from django.db import migrations, models
import sp3d.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0064_analysisexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisexport',
            name='file',
            field=models.FileField(blank=True, storage=sp3d.storage_backends.PrivateMediaStorage(bucket='sp3d-clients'), upload_to=digital.models.get_analysisexport_path),
        ),
        migrations.AlterField(
            model_name='bulkpartupload',
            name='file',
            field=models.FileField(blank=True, storage=sp3d.storage_backends.PrivateMediaStorage(bucket='sp3d-clients'), upload_to=digital.models.get_bulkpartupload_path),
        ),
    ]
