# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital', '0065_auto_20180110_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPartFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printable', models.CharField(choices=[('ALL', 'All'), ('IDENTIFIED', 'Identified'), ('PRINTABLE', 'Printable')], default='ALL', max_length=20)),
                ('analysis', models.CharField(choices=[('ALL', 'All times'), ('LAST', 'Last Analysis')], default='ALL', max_length=20)),
                ('obsolete', models.BooleanField(default=False, verbose_name='Obsolete Parts')),
                ('longtail', models.BooleanField(default=False, verbose_name='Longtail Parts')),
                ('viable', models.BooleanField(default=False, verbose_name='Financially viable')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_filters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='financialsettings',
            name='repricing_new_max_ratio',
            field=models.FloatField(default=0.5, verbose_name='Ratio to set new maximum betwwn cost+and max on repricing'),
        ),
    ]
