# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0067_auto_20180117_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpartfilters',
            name='reorder',
            field=models.CharField(choices=[('1', 'year 1'), ('2', 'year 2'), ('3', 'year 3'), ('4', 'year 4'), ('5', 'year 5')], default='', max_length=100),
        ),
    ]
