# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0068_userpartfilters_reorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='reprincing',
            field=models.BooleanField(default=False, verbose_name='Repricing Authorized'),
        ),
    ]
