# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0069_financialsettings_reprincing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialsettings',
            old_name='reprincing',
            new_name='repricing',
        ),
    ]
