# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0070_auto_20180119_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='year_restocking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year need restocking'),
        ),
    ]
