# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0071_financialcard_year_restocking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpartfilters',
            name='reorder',
            field=models.CharField(default='', max_length=100),
        ),
    ]
