# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0073_userpartcolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpartfilters',
            name='sort',
            field=models.CharField(default='', max_length=100),
        ),
    ]
