# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0075_auto_20180123_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpartupload',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkpartupload',
            name='finished_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkpartupload',
            name='total_entries',
            field=models.IntegerField(default=0),
        ),
    ]
