# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0076_auto_20180124_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkpartupload',
            name='total_entries',
        ),
    ]
