# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0077_remove_bulkpartupload_total_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpartfilters',
            name='appliance_list',
            field=models.TextField(blank=True, default='', verbose_name='Appliance Type List'),
        ),
        migrations.AlterField(
            model_name='userpartfilters',
            name='parttype_list',
            field=models.TextField(blank=True, default='', verbose_name='Part Type List'),
        ),
        migrations.AlterField(
            model_name='userpartfilters',
            name='reorder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpartfilters',
            name='sort',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
