# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0078_auto_20180124_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpartfilters',
            name='material_list',
            field=models.TextField(blank=True, default='', verbose_name='Material List'),
        ),
        migrations.AddField(
            model_name='userpartfilters',
            name='technology_list',
            field=models.TextField(blank=True, default='', verbose_name='Technology List'),
        ),
    ]
