# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0079_auto_20180201_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='blacklist',
            field=models.CharField(default='', max_length=600),
        ),
    ]
