# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0080_parttype_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttype',
            name='blacklist',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
