# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_currency'),
        ('digital', '0084_delete_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organisation')),
            ],
        ),
        migrations.RemoveField(
            model_name='financialcard',
            name='part',
        ),
        migrations.AlterField(
            model_name='part',
            name='final_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='jb.FinalCard'),
        ),
        migrations.AlterField(
            model_name='part',
            name='financial_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='digital.FinancialCard'),
        ),
        migrations.AlterUniqueTogether(
            name='appliancefamilydetails',
            unique_together=set([('appliance_family', 'organisation')]),
        ),
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together=set([('name', 'organisation')]),
        ),
    ]
