# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0085_auto_20180219_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.Catalogue'),
        ),
    ]
