# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0086_part_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliancefamilydetails',
            name='replacement_cost',
            field=models.FloatField(default=300, verbose_name='Replacement Cost (US$)'),
        ),
    ]
