# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0087_appliancefamilydetails_replacement_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='positive_pex_analysis',
            field=models.BooleanField(default=False, verbose_name='PEX Analysis positive'),
        ),
        migrations.AlterField(
            model_name='appliancefamilydetails',
            name='retail_price',
            field=models.FloatField(default=300, verbose_name='Average Retail Price (US$)'),
        ),
    ]
