# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0088_auto_20180227_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='positive_shortage_analysis',
            field=models.BooleanField(default=False, verbose_name='Shortage Analysis positive'),
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='avg_shortage_duration',
            field=models.FloatField(default=3, verbose_name='Average Shortage Duration (in months)'),
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='shortage_volume_loss_ratio',
            field=models.FloatField(default=0.2, verbose_name='loss ratio of customers during the shortage'),
        ),
    ]
