# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0089_auto_20180227_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancefamilydetails',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ApplianceFamilyDetails', to='users.Organisation'),
        ),
    ]
