# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0090_auto_20180228_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='cost_saving_pex',
            field=models.FloatField(default=0, verbose_name='Pex Cost Saving'),
        ),
        migrations.AddField(
            model_name='financialcard',
            name='cost_saving_shortage',
            field=models.FloatField(default=0, verbose_name='Shortage Cost Saving'),
        ),
    ]
