# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0091_auto_20180228_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='shortage_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Shortage Volumes'),
        ),
    ]
