# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0092_financialcard_shortage_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcard',
            name='pex_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='PEX Volumes'),
        ),
    ]
