# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0094_auto_20180228_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpartfilters',
            name='pex',
            field=models.BooleanField(default=False, verbose_name='PEX Parts'),
        ),
        migrations.AddField(
            model_name='userpartfilters',
            name='shortage',
            field=models.BooleanField(default=False, verbose_name='Shortage Parts'),
        ),
    ]
