# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0096_auto_20180327_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='catalogue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.Catalogue'),
        ),
        migrations.AlterField(
            model_name='userpartcolumns',
            name='cost_saving_pex',
            field=models.BooleanField(default=False, verbose_name='Cost saving Pex'),
        ),
    ]
