# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0097_auto_20180328_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsettings',
            name='repricing',
            field=models.BooleanField(default=True, verbose_name='Repricing Authorized'),
        ),
    ]
