# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0100_auto_20180420_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='show_financial',
            field=models.BooleanField(default=True, verbose_name='Show Financial Cards'),
        ),
    ]
